run:
  timeout: 5m
  skip-dirs:
    - bin
issues:
  exclude-use-default: false
linters-settings:
  revive:
    rules:
      - name: exported
        severity: error
      - name: dot-imports
        disabled: true
linters:
  enable:
    - revive