chainlink:
  image:
    image: public.ecr.aws/chainlink/chainlink
    version: 0.10.14
  web_port: 6688
  p2p_port: 8090
  resources:
    requests:
      cpu: 300m
      memory: 768Mi
    limits:
      cpu: 450m
      memory: 1024Mi
db:
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 350m
      memory: 1024Mi
replicas: 1

