chainlink:
  replicas: 1
  image:
    image: public.ecr.aws/chainlink/chainlink
    version: 0.10.14
  web_port: 6688
  p2p_port: 8090
  resources:
    requests:
      cpu: 1000m
      memory: 1000Mi
    limits:
      cpu: 1000m
      memory: 1000Mi
db:
  resources:
    requests:
      cpu: 1000m
      memory: 1000Mi
    limits:
      cpu: 1000m
      memory: 1000Mi

