{{ if .Values.chainlink.versions }}
{{- range $idx, $ver := .Values.chainlink.versions }}
  {{- include "chainlink.deployment" (dict "Values" $.Values "Release" $.Release "ver" $ver "idx" $idx) }}
{{ end }}
{{ else }}
  {{- include "chainlink.deployment" (dict "Values" $.Values "Release" $.Release "ver" $.Values.chainlink.image.version "idx" 0) }}
{{ end }}