apiVersion: v1
kind: Service
metadata:
  name: chainlink-service
{{/*  generateName: chainlink-*/}}
spec:
  ports:
    - name: node-port
      port: {{ .Values.chainlink.web_port }}
      targetPort: {{ .Values.chainlink.web_port }}
    - name: p2p-port
      port: {{ .Values.chainlink.p2p_port }}
      targetPort: {{ .Values.chainlink.p2p_port }}
  selector:
    app: chainlink-node
  type: ClusterIP